version: '3.8'

services:
  api:
    build: ./api
    container_name: tobacco_api
    hostname: api  # Важно для внутреннего DNS
    ports:
      - "80:80"
    volumes:
      - ./api/data:/api/data
    healthcheck:  # Добавляем healthcheck
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: "./api/.env"
    restart: unless-stopped
    image: vdilchenko/hookah_tbot_api
 
  bot:
    build: ./bot
    container_name: tobacco_bot
    hostname: bot
    env_file: "./bot/.env"
    depends_on:
      api:
        condition: service_healthy  # Ждем пока API станет доступен
    restart: unless-stopped
    network_mode: host
    image: vdilchenko/hookah_tbot_bot

networks:
  default:
    name: tobacco_network